apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: myns
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}